apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app2
  namespace: openshift-gitops
  labels:
    app: nodejs-app2
    cluster: hcp-cluster
spec:
  project: default
  source:
    repoURL: https://github.com/partojalili/ocp-hcp-gitops.git
    targetRevision: main
    path: deployments/nodejs-app2
  destination:
    name: hcp-cluster
    namespace: nodejs-app2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
