---
apiVersion: v1
kind: Namespace
metadata:
  name: webserver-prod
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: webserver-app
  namespace: webserver-prod
spec:
  type: Git
  pathname: https://github.com/partojalili/rhacm-workshop.git
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: ocp-hcp-cluster
  namespace: webserver-prod
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            name: ocp-hcp
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: webserver-app-prod
  namespace: webserver-prod
  labels:
    app: webserver-app
  annotations:
    apps.open-cluster-management.io/github-path: 04.Application-Lifecycle/exercise-application/application-resources
    apps.open-cluster-management.io/git-branch: master
spec:
  channel: webserver-prod/webserver-app
  placement:
    placementRef:
      kind: Placement
      name: ocp-hcp-cluster
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: webserver-app
  namespace: webserver-prod
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - webserver-app
