apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.clusterName }}-hosted-cluster
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: ${{ values.clusterName }}
    app.kubernetes.io/managed-by: backstage
    provisioned-by: developer-hub
spec:
  project: default
  source:
    repoURL: ${{ values.repoUrl }}
    path: clusters/${{ values.clusterName }}/base
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: clusters-${{ values.clusterName }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
