apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: partojalili/${{ values.name }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - nodejs
    - express
    - jwt
    - authentication
    - mongodb
  links:
    - url: https://github.com/${{ values.repoUrl | projectSlug }}
      title: GitHub Repository
      icon: github
    - url: https://devspaces.apps.cluster-r8knr.dynamic2.redhatworkshops.io/#https://github.com/${{ values.repoUrl | projectSlug }}
      title: Open in Dev Spaces
      icon: catalog
spec:
  type: service
  lifecycle: experimental
  providesApis:
    - ${{ values.name }}-api

---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{ values.name }}-api
  description: REST API for ${{ values.name }}
  tags:
    - rest
    - jwt
spec:
  type: openapi
  lifecycle: experimental
  definition: |
    openapi: 3.0.0
    info:
      title: ${{ values.name }} API
      version: 1.0.0
      description: ${{ values.description }}
