---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hcp2-ssh-key
  namespace: clusters-hcp2
spec:
  encryptedData:
    id_rsa.pub: AgAP3jEbyeRudSMAWeo4hq41SEWPZrVeu6unnxVeysplR164LxK6r11w3dAXsBIXThG9MZzWgdPk0VDpenS4DP6RlZZSMwMb00nLJzbBAHRsv/Fbltvr7t5beKz1tcF9EPs9zhWIZbBfdDdbzjhUxEOepETgLKYxziCTrzNrvV6nFHkY2WtiCr446+/aB9PW1L9a+rIap/lupm01sMrUoBzxelH+oBEvQ+U8BVIXG78fdbzEh/r28g/c0ehTY5ZY++MvQJVizfp23CF0KyWeE5hNOEnyuLhy/6Lf84W/310nrEz887SPLV941bvypzzubmxF2U973egYJGfBfBHpZL5qh8yQ2hoAsMX8aK34sWzH/VN59d4I+OA9ihXe+wdi8mlqsprexQVIlxL/W/auVE/GpXygHWcX60lQPvvPfGLJ6qwZfSLvHLoJGZ4jjNfkivky4OFQW4zO9GFbpg/y30fb6cDXh6/f3rfQh5S7+EQZqlZjJlyL6SkjaDpWZ3l3fGEGauRq5Sr4Ttd6LcNEuc44ZRCAAe+rOC+lMbjU/3XwMyIJQ3qBDVGjowAGJWK96guuoksjIt7+LuErADF9z8S5xKob5tPjChn3Yk7Xo+fFNGlbR0kGKq2lWspZWwKbCvrWot1JiYCsrv11tyfBjlAF5fPd3ifEzRBT/96FzXJpnwCArQ2m5kSEHIlmKv/W4olzR0f4cy3gPQDkTQ921BOnAXLaQ+Imk1g1yCi7Jh3XLpJQDJ4wOysU1VefVvVL+T5jUVrsqkwRZS/jGLmiWuvTbzOYBU8/lPO7At3By43OqE9vvqrXXYj+D8d9CzKojMZNSgMD4g==
  template:
    metadata:
      name: hcp2-ssh-key
      namespace: clusters-hcp2
