---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-cluster-ssh-key
  namespace: clusters-my-cluster
spec:
  encryptedData:
    id_rsa.pub: AgAypPgCAo06rvbSFYmt4a0+fBdsliMieYOW8Vdwsa3Z6Ch6S4W6th7CRpcgDDJS7RlHFmSJi/MrgRckQ0C0zo34ZGon3R8JBgF82WeQ1xx/WjGg3P32fFnE5ONgGmnxFjqdU9d8duuHhwRVd1gA5EvTqnKsdS9Z2WaF3GYMgvTaHLq3uyFmHZKmM3ZxkxE4KVQhuwHn4B/9nQCGvQrihON+nKt+cgTc6icMSuT+Z13g9zVz+hTkV3i3tWslKu2VEXzgyn9lIfEefGXMD0whJqyqiMVPcfYysVbYoMvVTVw8463GnnkkadvmcdyLurVfk06791wos8NxCABcTMp1GbTTEnGWgeCIyBh2ADUKXTBfcFaBE5MJIa2HAbHe/Jw2X8yw2q9jaJm+ihIfq0TEm3qicvyO5vN92TlujXA5oskJIFyatiXhrPnRZWfBgyxpcObJ8Xgqpqp0WrqP2Fye11dRBCsI70+wOY7NFUrKrhJjEVnmtWzWCnLG3UjJX+WKJDXALieZX/YYrFOpeAQhfFrdbW/yN02hjyXu+ZPRvRWw2+xngNap2bKvNWSbBRLQt+DbV0IFJwnjRI7/ijzgl/0Xhm8SV3LGTPLnqn69UY9Lxvm039CepZDuB+E3op6k4vKjRwwMb2MZ4gdhb+cDpQMSQ3C1xJqEZ2CfFP9VZwNpERNdBk67sNhAmjq5V5gGEMYg8og1gesFVwTCOlTIHrgdS8rYeaz5iuB6p77YC2mz1U3D2xWey10uHtIS8qLxTwAZWSe5v4sHs+JlmJAM+zt7IwVx5RLzU0XzjL2pT0eRnWsUBck5KDV81ShiWMB3N6vZLDaUsQ==
  template:
    metadata:
      name: my-cluster-ssh-key
      namespace: clusters-my-cluster
