---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-cluster-ssh-key
  namespace: clusters-my-cluster
spec:
  encryptedData:
    id_rsa.pub: AgCRjHdf/J5IprvdBhqcc7HHPr8S166Ns/mDabNVDlMaG3I9ikeYCf5iC4AhoN/UKF4zFoUv0y00lcVT7VvAcoQlMxLI83GZY1lBdA2Yg0wa1nQDwhXOxcWBIdfR0ZPhbxS/tf1rxonvSVSfLS8Y8oqegj5ckdxsRZhQqcE5eckyKaHAhMZCq5zfPEsA8U8EOXMCCrpmTVaftfmpC3gWI+6QXa4aAxWrQnzuGTPWREyM5JdXoHIrzSTgkwLB/rGRheEVWGETlJRpKWdqoNyn4ubfVkXRM0Y6X7t+O5D8T7ahC+XMNnPH4ygukFrQ14MFlZlBvoleDeQL0izU5kjQKWUJ4xQC70+r0sU03Mf5+/oZg6iz6twtI5Tq1OVD6ecTULtuPfh+59wuDoIJ9nfucRn/Fo2J/FtL/qfxjbZZd1utvGZKNIV6MZDrLy+2ld9lj6xRplS3/mq1y2bskRETM6IJSERdiAFNwj4HLPwQlHRkDfb28gRSCfncd+jPqceuJ+a9gHwlvdBWzOMC48Fn7TpzlGZGDwwi4RxxBcAvdi+qmYS515SgNl/wJK6v8p+wSMbpmWC1SLFVHk6Z/gt/cViud1+xyb2WheH/zB8TCn9wyCjQaTHVUYIc+dKXLalg3YYzL8CbOVgXZr/wraGL9oTEhWT1buTFGMQCCOW/E22PcgjI9Ec297+DYsR/52sculiUUeFcn1m3wfXK+bR34mPhECxWhoogv/P+UcroUbzdMAPEQGMgGRcbUrryPE0cR0+9pzvW9NKVNkEZ++NVj5a9Kn8SLxLDybVyX3lCyWrvYeRiDF7A7Ze8Wt7q5vnjOJYgs1BB0g==
  template:
    metadata:
      name: my-cluster-ssh-key
      namespace: clusters-my-cluster
