apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devhub3-hosted-cluster
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/partojalili/ocp-hcp-gitops.git
    targetRevision: HEAD
    path: clusters/devhub/devhub3/base
  destination:
    server: https://kubernetes.default.svc
    namespace: clusters-devhub3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
