apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nodejs-app-dev
  namespace: nodejs-app
  labels:
    app: nodejs-app-dev
spec:
  to:
    kind: Service
    name: nodejs-app-dev
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
