apiVersion: v1
kind: Service
metadata:
  name: nodejs-app5
  namespace: nodejs-app
  labels:
    app: nodejs-app5
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: nodejs-app5
