apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: nodejs-app6-build-deploy-
  namespace: nodejs-app6
  labels:
    app: nodejs-app6
    tekton.dev/pipeline: nodejs-app6-build-deploy
spec:
  pipelineRef:
    name: nodejs-app6-build-deploy
  params:
    - name: GIT_URL
      value: https://github.com/partojalili/ocp-hcp-gitops
    - name: GIT_REVISION
      value: main
    - name: IMAGE_NAME
      value: quay.io/pjalili/nodejs-app
    - name: IMAGE_TAG
      value: $(context.pipelineRun.name)
    - name: APP_PATH
      value: apps/nodejs
    - name: DEPLOYMENT_NAMESPACE
      value: nodejs-app6
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: dockerconfig
      secret:
        secretName: registry-credentials
