apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hcp-cluster-pull-secret
  namespace: clusters-hcp-cluster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hcp-secrets-store
    kind: ClusterSecretStore
  target:
    name: hcp-cluster-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  dataFrom:
    - extract:
        key: ocp-pull-secret
