apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hcp-cluster-ssh-key
  namespace: clusters-hcp-cluster
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hcp-secrets-store
    kind: ClusterSecretStore
  target:
    name: hcp-cluster-ssh-key
    creationPolicy: Owner
  data:
    - secretKey: id_rsa.pub
      remoteRef:
        key: ocp-ssh-key
        property: ssh-publickey
