apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gcp-cluster-cluster
  namespace: openshift-gitops
  labels:
    cluster-name: gcp-cluster
    platform: gcp
    region: us-east1
spec:
  project: default
  source:
    repoURL: github.com?owner=partojalili&repo=ocp-hcp-gitops
    targetRevision: main
    path: clusters/gcp/gcp-cluster/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gcp-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
