apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: gcp-cluster
  description: OpenShift cluster on GCP - gcp-cluster
  annotations:
    github.com/project-slug: partojalili/ocp-hcp-gitops
    backstage.io/techdocs-ref: dir:.
  tags:
    - openshift
    - gcp
    - kubernetes
    - us-east1
  links:
    - url: https://console.cloud.google.com/home/dashboard?project=openenv-jdpff
      title: GCP Console
      icon: cloud
    - url: https://console-openshift-console.apps.gcp-cluster.jdpff.gcp.redhatworkshops.io
      title: OpenShift Console
      icon: dashboard
spec:
  type: kubernetes-cluster
  lifecycle: production
  system: infrastructure
  metadata:
    platform: gcp
    region: us-east1
    version: 4.22.1
    workerCount: 3
    workerType: n2-standard-4
    masterType: n2-standard-4
    createdAt: ${{ '' | now }}
