apiVersion: v1
baseDomain: jdpff.gcp.redhatworkshops.io
metadata:
  name: gcp-cluster
platform:
  gcp:
    projectID: openenv-jdpff
    region: us-east1
controlPlane:
  name: master
  platform:
    gcp:
      type: n2-standard-4
  replicas: 3
compute:
- name: worker
  platform:
    gcp:
      type: n2-standard-4
  replicas: 3
networking:
  networkType: OVNKubernetes
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  serviceNetwork:
  - 172.30.0.0/16
  machineNetwork:
  - cidr: 10.0.0.0/16
pullSecret: 'PULL_SECRET_PLACEHOLDER'
sshKey: 'SSH_KEY_PLACEHOLDER'

publish: External
