apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.clusterName }}-pull-secret
  namespace: clusters-${{ values.clusterName }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    ${{ values.pullSecret }}
