apiVersion: v1
kind: Secret
metadata:
  name: ${{ values.clusterName }}-ssh-key
  namespace: clusters-${{ values.clusterName }}
type: Opaque
stringData:
  id_rsa.pub: |
    ${{ values.sshPublicKey }}
