apiVersion: v1
kind: Secret
metadata:
  name: devhub1-ssh-key
  namespace: clusters-devhub1
type: Opaque
stringData:
  id_rsa.pub: |
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDFlXxqRdBkrrFWNADt0p6vu0TN9q5wC4TXsHXagfrPwkKM0tta+UH91ZiOMGIINKYQJj8VZne2v6NbdBklUEJhQSeoPjQRF9D7/XUVW9LGuVCbwQvmaVI5S6AFy9j6zq+t0iUhYcwtVB58aaxLr27ZGnQACcFahCAYm8a8+Wuv2vaoe0wRRvI57oljpaRpaq15k0/9YBAPdgjhn5drBkIcXbuujv7+AD024R3r+T4C9K7Ty6ZIMvNSdTHBwxkxVb7qG3Rb5LW/kfUdfptnGo7Cbmuwk4WydAtlI28MN/d5xACAoakfpID2Ft/CNYaU0sUL92KGwjXWbnF4R1BBYGJodJjclv0ty9KUPL0w6mYgQMCSKKGmWN0ggcv3959A42jj6wsGPHjkaw90Gj2R5jMEzJr8knWv+WjDT2d7XZgC2eBTXWWMm7qL3pZo5dULohAxkM8a9HQqx/td0QmbtswZOnmIhc0sqlK8dPaM5Jf/F6vX7AhtRRiqu5hfgaB0DWFMc6iHhcbk0JoxKVuzrkFDfCSN73NXnOevBZP/gtw7D+gIY9LaoqvUtdAccwY3lIgwpFQTnB2q6QTyfU2/KLptf6TQZ7du0RHLm3NomN3PEnvVAkNmwW71aqI1ul8l66JGKGFTlzVR1yeaTDOcPWOwn2XDZQkFLJ2K/5KjbdqGDQ== pjalili@pjalili-mac
