apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${{ values.clusterName }}-gcp-creds
  namespace: ${{ values.clusterName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hcp-secrets-store
    kind: ClusterSecretStore
  target:
    name: ${{ values.clusterName }}-gcp-creds
    creationPolicy: Owner
  data:
    - secretKey: osServiceAccount.json
      remoteRef:
        key: gcp-service-account
        property: service-account.json
