apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: ${{ values.clusterName }}
  labels:
    cloud: GCP
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: global
    name: ${{ values.clusterName }}
    platform: gcp
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
