apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${{ values.clusterName }}-ssh-key
  namespace: ${{ values.clusterName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hcp-secrets-store
    kind: ClusterSecretStore
  target:
    name: ${{ values.clusterName }}-ssh-private-key
    creationPolicy: Owner
  data:
    - secretKey: ssh-privatekey
      remoteRef:
        key: ocp-ssh-key
        property: ssh-publickey
