apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nodejs-deployments
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/partojalili/ocp-hcp-gitops.git
        revision: main
        files:
          - path: "deployments/*/deployment-config.json"
  template:
    metadata:
      name: '{{name}}-{{targetCluster}}'
      labels:
        app: '{{name}}'
        target-cluster: '{{targetCluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/partojalili/ocp-hcp-gitops.git
        targetRevision: main
        path: 'deployments/{{name}}'
      destination:
        name: '{{targetCluster}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
