apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webserver-prod-ocp-hcp
  namespace: openshift-gitops
spec:
  project: default

  source:
    repoURL: https://github.com/partojalili/rhacm-workshop.git
    targetRevision: master
    path: 04.Application-Lifecycle/exercise-application/application-resources

  destination:
    server: https://kubernetes.default.svc
    namespace: webserver-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: route.openshift.io
      kind: Route
      jsonPointers:
        - /status
