apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.clusterName }}-cluster
  namespace: openshift-gitops
  labels:
    cluster-name: ${{ values.clusterName }}
    platform: gcp
    region: ${{ values.gcpRegion }}
spec:
  project: default
  source:
    repoURL: ${{ values.repoUrl }}
    targetRevision: ${{ values.gitBranch }}
    path: clusters/gcp/${{ values.clusterName }}/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ${{ values.clusterName }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
