apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${{ values.clusterName }}-pull-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hcp-secrets-store
    kind: ClusterSecretStore
  target:
    name: ${{ values.clusterName }}-pull-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ocp-pull-secret
