apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nodejs-app6

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  
  - route.yaml
  
  
  - pipeline/pipeline.yaml
  - pipeline/eventlistener.yaml
  

commonLabels:
  app: nodejs-app6
  app.kubernetes.io/name: nodejs-app6
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: nodejs-app6
  app.kubernetes.io/managed-by: argocd
