apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nodejs-app4
  namespace: openshift-gitops
  labels:
    app: nodejs-app4
spec:
  generators:
    - list:
        elements:
          - cluster: hcp-cluster
  template:
    metadata:
      name: 'nodejs-app4-{{cluster}}'
      labels:
        app: nodejs-app4
        target-cluster: '{{cluster}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/partojalili/ocp-hcp-gitops.git
        targetRevision: main
        path: deployments/nodejs-app4
      destination:
        name: '{{cluster}}'
        namespace: nodejs-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: nodejs-app4-placement
  namespace: openshift-gitops
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            name: hcp-cluster
