apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: gcp-cluster
  namespace: gcp-cluster
spec:
  clusterName: gcp-cluster
  clusterNamespace: gcp-cluster
  clusterLabels:
    cloud: GCP
    vendor: OpenShift
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
