apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pull-secret.yaml
  - ssh-key.yaml
  - gcp-creds.yaml
  - install-config.yaml
  - clusterdeployment.yaml
  - managedcluster.yaml
  - klusterletaddonconfig.yaml
