apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: gcp-cluster
  labels:
    cloud: GCP
    vendor: OpenShift
    cluster.open-cluster-management.io/clusterset: global
    name: gcp-cluster
    platform: gcp
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
