---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-github-secret
  namespace: rhdh-operator
spec:
  encryptedData:
    GITHUB_TOKEN: AgCZZ4yznOF+vJX/iWKh3AsfMn3ypM7dILnGZzi4HZJaDb1H2RQ8haGpL8gaZtIG13+vluMuKt6s+X1TDDRAA26gwrKfa3mTPaLHwocHUyAQqZZB0YW1ApfpA8llFFYBU0bV2NsM5dtK4aA1k1UlPqQPLLO3PfovGVmpeNF+OytsdSuGNtqAkK1DYM21bvarMkJZZMlZRxN5eTRSbcdwhlpNEpDkpxS2p1tlKJFGwgY47qxgdy/DT17Pi1olO7bgX90t9+JQE4CfwfQtqUgqNH3Xf6b3gb4ZJDncz1M9OI++R7pCNSo2eqN4BnT6CeBA0wRfUQ7pNOfZ7xGwICkaiaDBZjaW4Mv5zbFFJJzNn1wgRXaelW4R8LIFoMSza7c6wOSiCI958i7aka32DjMBXT6ZOmMRvijzIljq6RNAxr9soqOulDUDJFkbNoX++tWIuuf+y8u2D2Cg3sZnHc88WWhGhncAd26kiOQ1ANP5YFNubjkO2C+jphF4GVgTapkfiKv6nBQQ6P0Qrp3uK4dyoBdCGFsOc7ax0FGCRpO0IWmhbEgCy15+EJAYjfCI/RrvqyMkZJlMY7us7ToMXY1RgICqQazGivTiWIxyJzaVYKGdpfk9LYsQw/Apt0heJzLAKGpOMg2y+80r8HdjO+e8+4iSXG9TXaI5mnC30+aOuy8By75skozuaGMgXzEs7Y425fbH5ZcxGn2fbprO5XuF7kg22MCR1FID2HVeSCEZ4bct7U03u4m0noee
  template:
    metadata:
      name: backstage-github-secret
      namespace: rhdh-operator
    type: Opaque
