---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-github-secret
  namespace: rhdh-operator
spec:
  encryptedData:
    GITHUB_TOKEN: AgBEx9vQKBik4hB1HA3A3N/l5fRZ9NPOG5xVvFscaAJqqEK+YKmvgYhJ2zyi5pJtANH5e2+/nYRpQPW5Vee8RrZyiXwcLRLPKHKb9OTCFLL7sqCT25t3bY9btGlrpJsjPXxfqMLlp59Apb/mb63RhXAZzw25B2zVF6LFWCvbz4U03JS+TjBXdv1JhDlQQm/IpvwJeF/xgpGbaIJqMQbr5ukasEojGAeRDYPr4gs6Di3xsuDkpHgeXKGLVxiETUrOH2rNaOLh3FSK/2WHxXKBhczAH869PVNavPfY/bo9eDX/kk/OP3DkKqzEuL+pPjN2t725b2bwfFI/nypgzrcWAaLXYPKzWGq4ULrwmw389DxX9d77Tb5AWeHLjF5R8Yzh7rAk+Ak/ck7hk0BhrWTGwNbyRYVMSlJcNrtTRdvFj1/qPhY3cvb7QW7z9K1WG3BsbnnoSONgzMGo5S4q/V9PMP95aF0PLBfYMAjSv7bAASdRsxyoC9lebvMQtAtP8TJlhfBtB1qB8cXzI4vQfKrA00iExrcgMsxkxeUsI64eVTnIpTqyMyt0FrN1X09zsmhylJejZL0WPv+/CKzYxWhhgrLiI8w/8vopsYF6+M8pQ2lwsVJU623MfczD6gUV+xrE6Ry+FQnaDflqU5EGEPkW0+B8JQ/SlxSvHWGhiq+7EM9YDHp76fPGYeRchDIkE7TMGohLmZ9LQy7MSi4t/U/p2ga+3QLM5CdPjMWCMbtK77n1WNqPeO8/VBP6
  template:
    metadata:
      name: backstage-github-secret
      namespace: rhdh-operator
    type: Opaque
