---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-github-secret
  namespace: rhdh-operator
spec:
  encryptedData:
    GITHUB_TOKEN: AgCeyVjj6LaBj1n3Bscb1DI4tb7K4nHt6gQYomvX2A98ZJ6qZiU5fAMFLSlDXwh2L22SWvuVd83pKDCbcSJ0Ta9+U+aNScXeg6fasyaBk/Oc1XKIEkThHiGYcbalL6+YTGwNzXkOuGABpyGeCx2+vv0m0tYkqw5MHcHRFuxuKsYnDztFSiS/Tae/mF+ytntcFZ0aGR5NIZAI9d6V2reaNZlbYZwY0gDlr/H6Lc2AOAqR4ZCo6Jit4OpTkaNQfwt6zU/E4bggPNwmitPUJsxdCH58OOt3NlOCL5zgTXbbXog2C/myhzqE4lftArepHcGaO+zeJvZYP13CuRJqo0X4vgqPmTE8MHUmfteuI5QPy1lPONbpQG7Jb1ZmL7cOIXZ5mrxoXl1GseqSWKYqh3soOu/OIPuXErSYP3ojbnnxniGI2P2mrLZLzCV/8eSesjdHoR446BaPdaaE+dW5xSlj0b9MW1pWG9c4NvWL3gk54McvQOeESmMdEFZ+IB36XbeSwKHAACDy9CpvRCd6DmP5rwPM48Xx9dzO6hv4v/mq3HAEHEl36eg1B8pfKq0579w6YNu1oXhNBrKoC4JDqloSbJ95Aqym23DDyE8fG/HxwKFW9nvAJ8e6FKwkf/JTgHTKv+NTTHRskz7gcTqkYGMn8CcMDmRF+53i9Z4dc6c4C/PIJWx5LWoWKzWGDJRIir2Qv1G8wm0qRVqEOH2GK5v/lac+sGiMGcocRbt2DmJaEHS6JRsQtoVhzVTZ
  template:
    metadata:
      name: backstage-github-secret
      namespace: rhdh-operator
    type: Opaque
