apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-guest-auth-config
  namespace: rhdh-operator
data:
  app-config-guest.yaml: |
    auth:
      environment: development
      providers:
        guest:
          dangerouslyAllowOutsideDevelopment: true
    signInPage: guest
