---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hcp-ssh-key
  namespace: clusters
spec:
  encryptedData:
    id_rsa.pub: AgCAVZZ6ic9+N3T3MkUWOu5X6T5qeRcwoRA9dmxpywSTeCLvkKsLZ+vjxb9sJD6fZzU7jEI7sUV2ndf8SLZE0ipEyF8QkMq4zPvsv9FHGYhPTIvlQ9bO0JY3es/Kv6Dwvjq2t+NLeFZmFBegPwOiDZnsqKFA9ggf0v4VCpPbM0sEvpLgIjS+JrtzMDvmOA5A3y5ZFDvUlFrEx+cbAYF0oEeIhAd4mAQx1E7nRSRRaCzxgU/Ue2DcZpMsW9YUDLYxrc/LU3AagRwxyhN+Fmgp2CvilVp+PUfup+fdxlSUlAcoyQT0YSi1JW0VKAIi9Vvz3XCys0uzsvKiI3/ocndZonzFmzbpazQh1VBkTUcnaJ6qOl2TuLEgQM3/vxaEqVARwchthpxLeo9R2NcgcLT1OWQvfhlEXdTPBh+uFOSXCfUNqcTaKHLvVX2NKahOV5ITf/6eJTNdX21MQsIQjMLpOaJxsTkXyPCP8mF71wWsHBMTdybLildVvYzjnyQt3e3cZx1TpgCPnmHbaK+pW5jGeDjC5i66xwqYwchxu08pEXDNcxUK/0yuX/PTBBP0oiP6Hlx2Mv+m7xK8vMX38zAV/3DjTkLS7M+NgV6NKZ1uxmilnXt/A1PClOlK2PWhXgmMOmviWpkW9lb8YL7w+Yu4mvhfEG0JpAARO47Y5z4x2JyytagYxxN61bM0VLqyo9kJAJANHoo58dWS8Hbn2NB5OKRtaGiw+Ijj6GTM/EJcsXfnyX0AKfbi9R5Cqr1ZenO4Upww3t0c7UelS2YYA++c5hB0OGd8pALDVJOdSQkeTsCZq8unKAIaQyQ8T8+AOvKVGACf/bxbTA==
  template:
    metadata:
      name: hcp-ssh-key
      namespace: clusters
