---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hcp-ssh-key
  namespace: clusters
spec:
  encryptedData:
    id_rsa.pub: AgCUeTH2ftjOucMOxpU7xfJceiXRnrUL1JlDyk3fHTw4rakYtwLMF55DLslFMoVvWVXH4bw/OmRs1ymuAbIAv951bcOq5fNYafZtyIol5nSNyOV16XtnaADHEbB0TWUAmGed9DxS6mlrNzr2AA0dNOB9pH13e94Bg10mHW+pOfFZQp5ai/cXLl2jj6toWa6BIRWidC4vgkG9+dpYMo9w8GTlh/P+B/nkNWaXW1QQFSvkuJJKrBmdYK/PBgiCAKSjee7jako0DuqvC3zEvwQzWhhnFW9rtIIl9UZM0Q9BgccHG9xkzNBcNC4HPN6skwgNCIaegjjJ3M6sChYyqPeSHRvNa3F0WA/V6Bo46T9A8st93TsQnac7aHX9pLD+5CZA1ZDx8T6NbBfp+v/JdDJGjD/1xDnQJxIjmBCyfedVqZkgU5ewcm2Xw9BVQI5e/SB28uH+bAlQvptB3/DcMelF5IiCTft7a6I8f+I5xN585UgunS1P/FDQhxNXQSbd4iuFjDXV9Nn8fP+39mv/julS4RlBkrdS00mH0AY2jOT6AASs3fF9qVoRsIrGFVxQW9Q+VnlxnzA4XgR1W38v1gNYOWuiU7tB+o+5qYJrsNanW4ZMcop75KbASN2jsTCOKDvFmZFK9SJQmMQG8YaBKO9wh4zpi2U7WG/8FL5UiPVad5sRQFCp86Gl589UB48aQqGKpsFLREVzthGyfmujZDiiGkse7Wk4qCnuyLssw0Y5dGgqWxfv8aYSyhxfaWfyFs/ZxJHNYEXtiq41o3Qc5shcjidMAUoRRpHrON2KYcQMQnPmRG1PjgalFtG7nA566j0MIF/rHeVstg==
  template:
    metadata:
      name: hcp-ssh-key
      namespace: clusters
