apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: ${{ values.name }}-build-deploy-
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.name }}
    tekton.dev/pipeline: ${{ values.name }}-build-deploy
spec:
  pipelineRef:
    name: ${{ values.name }}-build-deploy
  params:
    - name: GIT_URL
      value: https://github.com/partojalili/ocp-hcp-gitops
    - name: GIT_REVISION
      value: main
    - name: IMAGE_NAME
      value: ${{ values.imageRegistry }}/${{ values.imageRepository }}
    - name: IMAGE_TAG
      value: $(context.pipelineRun.name)
    - name: APP_PATH
      value: apps/nodejs
    - name: DEPLOYMENT_NAMESPACE
      value: ${{ values.namespace }}
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: dockerconfig
      secret:
        secretName: registry-credentials
