---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hcp1-ssh-key
  namespace: clusters-hcp1
spec:
  encryptedData:
    id_rsa.pub: AgCE7QTutwFqkZ4hgLQi520ETnR5YcEcrZx8KArdq3u8B78RGaO5LgBenKS83N4bmB10qtqFri8cGH7Wa2TGUZk7iJCIK691zA0yk9JPxxORPPbLoriI89QttBOer0Fftv4Penhm+CQxqIHpU0SIOu4BsZ//A0aJ0xVzjNkE4XHRbz4NSqN5y5URpVGpi8NrZE7Ay8OTay8CxSRIP2raz1QQmugQufYk7gVqVxB8LeSUfJ0to5iHTmNG7SMABctChKcBh7u1LllMRov23Wi79bww1TbUAG/02zWxAPAV2WA3dB9hhsVVZinUBWGINwe3gUQ6+kMWWPRIW+gU0MpbP+7NmsMQANL8nhgY6RglwSRL52w4M0WoMA2S1xbYrtjuyy3kyVwbdsBEZ2Hk3PuZ9klRK5onWevwoOfEqzvnlpRE66xPBEXX8yqVZ/U+yW2MQvHmzqfBuipXM9o0uJMmY/LAV1ejz+9BY59E9Ev1TYM2McI+lLpq1RsXXHl8iasH/pAHL5FM1nkg8GSSVBqmVwtt+uaHCoQ1yRYLuYCXgjwOgnRZy6k0BlHBG4MyBbe+532mIqle36cs7u1r3Rmojp9lizh/sIvz4aZ65o3QqTpJ+QWlOGORsrBIpFev4TrJcBJ4j3296hcNvFMfO+OAMzJ+spduI+xXOnOcoZVfbz+zkB8UMBFHVnv4FS1YBLt00i7vfoDeHOVxYe0H+t2qMvU38hAevt0uVZq9+VtbnV9vszOtoVE9VyCygT5zpmr90AaYuuMm2Qe2IHMVTSCEmbXy/BnkizJVmLbdK0rVsVDIJNUTRfep/BQ/u4TbqK8C7vjt9oWp9Q==
  template:
    metadata:
      name: hcp1-ssh-key
      namespace: clusters-hcp1
