apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gcp-cluster1-gcp-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hcp-secrets-store
    kind: ClusterSecretStore
  target:
    name: gcp-cluster1-gcp-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: gcp-service-account
