apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gcp-cluster1-ssh-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: hcp-secrets-store
    kind: ClusterSecretStore
  target:
    name: gcp-cluster1-ssh-key
    creationPolicy: Owner
  data:
    - secretKey: ssh-publickey
      remoteRef:
        key: ocp-ssh-key
        property: ssh-publickey
