apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nodejs-app
  namespace: openshift-gitops
  labels:
    app: nodejs-app
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: nodejs-app-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: nodejs-app
      labels:
        app: nodejs-app
    spec:
      project: default
      source:
        repoURL: https://github.com/partojalili/ocp-hcp-gitops.git
        targetRevision: main
        path: deployments/nodejs-app
      destination:
        name: '{{`{{name}}`}}'
        namespace: nodejs-app
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: nodejs-app-placement
  namespace: openshift-gitops
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            name: hcp-cluster
